<template>
  <component
    :is="lucideIcon"
    v-if="lucideIcon"
    :class="iconClass"
    :size="size"
    :stroke-width="strokeWidth"
    aria-hidden="true"
  />
  <span v-else :class="iconClass" aria-hidden="true">{{ name }}</span>
</template>

<script setup lang="ts">
import { computed, useAttrs } from "vue";
import {
  Activity,
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  Bell,
  Blocks,
  Bot,
  Brain,
  Brush,
  CalendarX,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CirclePlus,
  CircleUserRound,
  CloudDownload,
  CloudUpload,
  Code,
  Compass,
  Copy,
  CornerDownLeft,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  FilePenLine,
  FilePlus,
  FileText,
  Folder,
  FolderPlus,
  Folders,
  Frown,
  Gauge,
  GitFork,
  History,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  Lightbulb,
  Link,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Menu,
  MessageCircle,
  MessagesSquare,
  Moon,
  Network,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  PanelTop,
  Pencil,
  Pin,
  Play,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Route,
  Ruler,
  Save,
  Search,
  SearchX,
  Server,
  Settings,
  Settings2,
  ShieldUser,
  Shrink,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  Telescope,
  Terminal,
  ToggleLeft,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  WandSparkles,
  X,
} from "@lucide/vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    name: string;
    size?: number | string;
    strokeWidth?: number | string;
  }>(),
  {
    size: 18,
    strokeWidth: 2,
  }
);

const attrs = useAttrs();

const materialToLucide: Record<string, string> = {
  account_circle: "CircleUserRound",
  account_tree: "GitFork",
  admin_panel_settings: "ShieldUser",
  add: "Plus",
  add_circle: "CirclePlus",
  add_circle_outline: "CirclePlus",
  add_link: "Link",
  archive: "Archive",
  arrow_back: "ArrowLeft",
  arrow_downward: "ArrowDown",
  auto_awesome: "Sparkles",
  auto_fix_high: "WandSparkles",
  animation: "Sparkles",
  autoplay: "Play",
  bookmark: "Bookmark",
  brush: "Brush",
  category: "Blocks",
  chat_bubble_outline: "MessageCircle",
  check: "Check",
  chevron_left: "ChevronLeft",
  chevron_right: "ChevronRight",
  close: "X",
  close_fullscreen: "Shrink",
  cloud_download: "CloudDownload",
  cloud_upload: "CloudUpload",
  code: "Code",
  compress: "Gauge",
  content_copy: "Copy",
  create_new_folder: "FolderPlus",
  dashboard: "LayoutDashboard",
  dark_mode: "Moon",
  delete: "Trash2",
  delete_forever: "Trash2",
  delete_sweep: "Trash2",
  description: "FileText",
  dns: "Server",
  download: "Download",
  edit: "Pencil",
  edit_note: "FilePenLine",
  error: "CircleAlert",
  event_busy: "CalendarX",
  expand_more: "ChevronDown",
  explore_off: "Compass",
  extension: "Puzzle",
  folder: "Folder",
  folder_copy: "Folders",
  forum: "MessagesSquare",
  history: "History",
  home: "House",
  hourglass_top: "Hourglass",
  image: "Image",
  inbox: "Inbox",
  info: "Info",
  inventory: "Package",
  inventory_2: "Archive",
  keyboard_arrow_down: "ChevronDown",
  keyboard_arrow_up: "ChevronUp",
  keyboard_return: "CornerDownLeft",
  keep: "Pin",
  lan: "Network",
  leaderboard: "ChartNoAxesColumnIncreasing",
  left_panel_close: "PanelLeftClose",
  left_panel_open: "PanelLeftOpen",
  lightbulb: "Lightbulb",
  light_mode: "Sun",
  link: "Link",
  lock: "Lock",
  logout: "LogOut",
  menu: "Menu",
  more_vert: "EllipsisVertical",
  network_check: "Activity",
  nights_stay: "Moon",
  note_add: "FilePlus",
  notifications: "Bell",
  open_in_new: "ExternalLink",
  person: "User",
  play_arrow: "Play",
  progress_activity: "LoaderCircle",
  psychology: "Brain",
  push_pin: "Pin",
  refresh: "RefreshCw",
  replay: "RotateCcw",
  restart_alt: "RotateCcw",
  right_panel_close: "PanelRightClose",
  right_panel_open: "PanelRightOpen",
  route: "Route",
  save: "Save",
  search: "Search",
  search_off: "SearchX",
  sentiment_dissatisfied: "Frown",
  settings: "Settings",
  settings_suggest: "Settings2",
  smart_toy: "Bot",
  straightening: "Ruler",
  straighten: "Ruler",
  swap_vert: "ArrowDownUp",
  sync: "RefreshCw",
  system_update: "Download",
  tag: "Tag",
  terminal: "Terminal",
  toggle_off: "ToggleLeft",
  travel_explore: "Telescope",
  tune: "SlidersHorizontal",
  upload: "Upload",
  upload_file: "Upload",
  view_agenda: "PanelTop",
  view_list: "List",
  visibility: "Eye",
  warning: "TriangleAlert",
};

const lucideComponents: Record<string, unknown> = {
  Activity,
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  Bell,
  Blocks,
  Bot,
  Brain,
  Brush,
  CalendarX,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CirclePlus,
  CircleUserRound,
  CloudDownload,
  CloudUpload,
  Code,
  Compass,
  Copy,
  CornerDownLeft,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  FilePenLine,
  FilePlus,
  FileText,
  Folder,
  FolderPlus,
  Folders,
  Frown,
  Gauge,
  GitFork,
  History,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  Lightbulb,
  Link,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Menu,
  MessageCircle,
  MessagesSquare,
  Moon,
  Network,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  PanelTop,
  Pencil,
  Pin,
  Play,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Route,
  Ruler,
  Save,
  Search,
  SearchX,
  Server,
  Settings,
  Settings2,
  ShieldUser,
  Shrink,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  Telescope,
  Terminal,
  ToggleLeft,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  WandSparkles,
  X,
};

const lucideIcon = computed(() => {
  const lucideName = materialToLucide[props.name];
  if (!lucideName) {
    return null;
  }

  return lucideComponents[lucideName] || null;
});

const iconClass = computed(() => [
  "app-icon",
  "material-symbols-outlined",
  attrs.class,
]);
</script>

<style scoped>
.app-icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  flex: 0 0 auto;
  vertical-align: -0.125em;
  stroke: currentColor;
}
</style>
